spring.profiles.active: dev

spring.jpa.hibernate.ddl-auto: update

ribbon:
  eureka:
   enabled: false

spring:
  application:
    name: attendees
    
# Using macros that are replaced by maven build
info:
  build:
    artifact: pcf-ers-demo1
    name: pcf-ers-demo1
    description: Core PCF ERS Demo
    version: 0.0.1-SNAPSHOT